#!/bin/bash

declare -A names

mkdir -p .logs/names

for i in $(./nodes);
do
  ssh "alarm@$i" "cat /usr/share/dict/cracklib-small | shuf -n 1 | tr -cd \"[:alnum:]._-\" > ~/name.txt" > ".logs/names/$i.out" 2> ".logs/names/$i.err" &
  names[$i]=$!
done

for ip in "${!names[@]}";
do 
  echo "Waiting for $ip at PID ${names[$ip]}"
  wait ${names[$ip]}
  echo "out:"
  cat ".logs/names/$ip.out"
  echo "err:"
  cat ".logs/names/$ip.err"
  echo "=================================================================="
done
