#!/bin/bash

declare -A updates

mkdir -p .logs/updates

for i in $(./nodes);
do
  ssh "root@$i" "pacman -Syu $1" > ".logs/updates/$i.out" 2> ".logs/updates/$i.err" &
  updates[$i]=$!
done

for ip in "${!updates[@]}";
do 
  echo "Waiting for $ip at PID ${updates[$ip]}"
  wait ${updates[$ip]}
  echo "out:"
  cat ".logs/updates/$ip.out"
  echo "err:"
  cat ".logs/updates/$ip.err"
  echo "=================================================================="
done
